language: ruby
rvm:
  - "2.1.1"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email:
    recipients:
      - "kerchner@gwu.edu"
    on_success: "change"
    on_failure: "always"
services:
  - redis-server
